name: Matthew Stasoff
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7491
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#d6d4d5'
    - '#9d9c9a'
    - '#1a1710'
    - '#3f5390'
  brandStrength: 0.25
  lightness: 0.897872663801536
  saturation: 0.9603982015978545
  rhythmicContrast: 0.5342353300657123
purpose: []
