name: null
favicon: null
layout_spectrum: 0.1992003854829818
typography_spectrum: 0.5814048093743622
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8140750108286738
  lightness: 0.897872663801536
  saturation: 0.9603982015978545
  rhythmicContrast: 0.5342353300657123
purpose: []
